
-- Users table
CREATE TABLE users (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  picture VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Files table
CREATE TABLE files (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  size INT NOT NULL,
  content_type VARCHAR(255) NOT NULL,
  data TEXT NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  connection_code VARCHAR(255) UNIQUE,
  status VARCHAR(50) NOT NULL DEFAULT 'WAITING_FOR_DOWNLOAD',
  expires_at TIMESTAMP NULL,
  download_url VARCHAR(255),
  download_expires_at TIMESTAMP NULL,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Failed attempts table
CREATE TABLE failed_attempts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ip VARCHAR(255) NOT NULL,
  attempts INT NOT NULL DEFAULT 0,
  last_attempt_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  timeout_until TIMESTAMP NULL,
  timeout_duration INT DEFAULT 0
);
